export const dataEntityTypes = [
  "users",
  "posts",
  "comments",
  "albums",
  "reviews",
  "todos",
  "addresses",
  "companies",
  "products",
  "payments",
  "vehicles",
  "files",
  "socialmediaprofiles",
  "educationalinstitutions",
  "financialtransactions",
  "healthrecords",
  "realestatelistings",
  "travelplans",
  "recipes",
  "orders",
] as const;

export const fakerFormats = [
  "json",
  "yaml",
  "xml",
  "html",
  "raw",
  "csv",
  "text",
  "form",
  "pdf",
  "markdown",
  "binary",
] as const;

export const supportedLocalization = [
  "af_ZA",
  "ar",
  "az",
  "base",
  "cs_CZ",
  "da",
  "de",
  "de_AT",
  "de_CH",
  "dv",
  "el",
  "en",
  "en_AU",
  "en_AU_ocker",
  "en_BORK",
  "en_CA",
  "en_GB",
  "en_GH",
  "en_HK",
  "en_IE",
  "en_IN",
  "en_NG",
  "en_US",
  "en_ZA",
  "eo",
  "es",
  "es_MX",
  "fa",
  "fi",
  "fr",
  "fr_BE",
  "fr_CA",
  "fr_CH",
  "fr_LU",
  "fr_SN",
  "he",
  "hr",
  "hu",
  "hy",
  "id_ID",
  "it",
  "ja",
  "ka_GE",
  "ko",
  "lv",
  "mk",
  "nb_NO",
  "ne",
  "nl",
  "nl_BE",
  "pl",
  "pt_BR",
  "pt_PT",
  "ro",
  "ro_MD",
  "ru",
  "sk",
  "sr_RS_latin",
  "sv",
  "th",
  "tr",
  "uk",
  "ur",
  "vi",
  "yo_NG",
  "zh_CN",
  "zh_TW",
  "zu_ZA",
] as const;

export const supportedLocalizationMap = new Map([
  ["af_ZA", ["Afrikaans (South Africa)", "fakerAF_ZA"]],
  ["ar", ["Arabic", "fakerAR"]],
  ["az", ["Azerbaijani", "fakerAZ"]],
  ["base", ["Base", "fakerBASE"]],
  ["cs_CZ", ["Czech (Czechia)", "fakerCS_CZ"]],
  ["da", ["Danish", "fakerDA"]],
  ["de", ["German", "fakerDE"]],
  ["de_AT", ["German (Austria)", "fakerDE_AT"]],
  ["de_CH", ["German (Switzerland)", "fakerDE_CH"]],
  ["dv", ["Maldivian", "fakerDV"]],
  ["el", ["Greek", "fakerEL"]],
  ["en", ["English", "fakerEN"]],
  ["en_AU", ["English (Australia)", "fakerEN_AU"]],
  ["en_AU_ocker", ["English (Australia Ocker)", "fakerEN_AU_ocker"]],
  ["en_BORK", ["English (Bork)", "fakerEN_BORK"]],
  ["en_CA", ["English (Canada)", "fakerEN_CA"]],
  ["en_GB", ["English (Great Britain)", "fakerEN_GB"]],
  ["en_GH", ["English (Ghana)", "fakerEN_GH"]],
  ["en_HK", ["English (Hong Kong)", "fakerEN_HK"]],
  ["en_IE", ["English (Ireland)", "fakerEN_IE"]],
  ["en_IN", ["English (India)", "fakerEN_IN"]],
  ["en_NG", ["English (Nigeria)", "fakerEN_NG"]],
  ["en_US", ["English (United States)", "fakerEN_US"]],
  ["en_ZA", ["English (South Africa)", "fakerEN_ZA"]],
  ["eo", ["Esperanto", "fakerEO"]],
  ["es", ["Spanish", "fakerES"]],
  ["es_MX", ["Spanish (Mexico)", "fakerES_MX"]],
  ["fa", ["Farsi/Persian", "fakerFA"]],
  ["fi", ["Finnish", "fakerFI"]],
  ["fr", ["French", "fakerFR"]],
  ["fr_BE", ["French (Belgium)", "fakerFR_BE"]],
  ["fr_CA", ["French (Canada)", "fakerFR_CA"]],
  ["fr_CH", ["French (Switzerland)", "fakerFR_CH"]],
  ["fr_LU", ["French (Luxembourg)", "fakerFR_LU"]],
  ["fr_SN", ["French (Senegal)", "fakerFR_SN"]],
  ["he", ["Hebrew", "fakerHE"]],
  ["hr", ["Croatian", "fakerHR"]],
  ["hu", ["Hungarian", "fakerHU"]],
  ["hy", ["Armenian", "fakerHY"]],
  ["id_ID", ["Indonesian (Indonesia)", "fakerID_ID"]],
  ["it", ["Italian", "fakerIT"]],
  ["ja", ["Japanese", "fakerJA"]],
  ["ka_GE", ["Georgian (Georgia)", "fakerKA_GE"]],
  ["ko", ["Korean", "fakerKO"]],
  ["lv", ["Latvian", "fakerLV"]],
  ["mk", ["Macedonian", "fakerMK"]],
  ["nb_NO", ["Norwegian (Norway)", "fakerNB_NO"]],
  ["ne", ["Nepali", "fakerNE"]],
  ["nl", ["Dutch", "fakerNL"]],
  ["nl_BE", ["Dutch (Belgium)", "fakerNL_BE"]],
  ["pl", ["Polish", "fakerPL"]],
  ["pt_BR", ["Portuguese (Brazil)", "fakerPT_BR"]],
  ["pt_PT", ["Portuguese (Portugal)", "fakerPT_PT"]],
  ["ro", ["Romanian", "fakerRO"]],
  ["ro_MD", ["Romanian (Moldova)", "fakerRO_MD"]],
  ["ru", ["Russian", "fakerRU"]],
  ["sk", ["Slovak", "fakerSK"]],
  ["sr_RS_latin", ["Serbian (Serbia, Latin)", "fakerSR_RS_latin"]],
  ["sv", ["Swedish", "fakerSV"]],
  ["th", ["Thai", "fakerTH"]],
  ["tr", ["Turkish", "fakerTR"]],
  ["uk", ["Ukrainian", "fakerUK"]],
  ["ur", ["Urdu", "fakerUR"]],
  ["vi", ["Vietnamese", "fakerVI"]],
  ["yo_NG", ["Yoruba (Nigeria)", "fakerYO_NG"]],
  ["zh_CN", ["Chinese (China)", "fakerZH_CN"]],
  ["zh_TW", ["Chinese (Taiwan)", "fakerZH_TW"]],
  ["zu_ZA", ["Zulu (South Africa)", "fakerZU_ZA"]],
]);

export const schemaProps = new Map([
  ["aircrafttype", "airline.aircraftType"],
  ["airline", "airline.airline"],
  ["airplane", "airline.airplane"],
  ["airport", "airline.airport"],
  ["flightnumber", "airline.flightNumber"],
  ["recordlocator", "airline.recordLocator"],
  ["seat", "airline.seat"],
  ["bear", "animal.bear"],
  ["bird", "animal.bird"],
  ["cat", "animal.cat"],
  ["cetacean", "animal.cetacean"],
  ["cow", "animal.cow"],
  ["crocodilia", "animal.crocodilia"],
  ["dog", "animal.dog"],
  ["fish", "animal.fish"],
  ["horse", "animal.horse"],
  ["insect", "animal.insect"],
  ["lion", "animal.lion"],
  ["rabbit", "animal.rabbit"],
  ["rodent", "animal.rodent"],
  ["snake", "animal.snake"],
  ["type", "animal.type"],
  ["cmyk", "color.cmyk"],
  ["colorbycsscolorspace", "color.colorByCSSColorSpace"],
  ["csssupportedfunction", "color.cssSupportedFunction"],
  ["csssupportedspace", "color.cssSupportedSpace"],
  ["hsl", "color.hsl"],
  ["human", "color.human"],
  ["hwb", "color.hwb"],
  ["lab", "color.lab"],
  ["lch", "color.lch"],
  ["rgb", "color.rgb"],
  ["space", "color.space"],
  ["department", "commerce.department"],
  ["isbn", "commerce.isbn"],
  ["price", "commerce.price"],
  ["product", "commerce.product"],
  ["productadjective", "commerce.productAdjective"],
  ["productdescription", "commerce.productDescription"],
  ["productmaterial", "commerce.productMaterial"],
  ["productname", "commerce.productName"],
  ["bs", "company.bs"],
  ["bsadjective", "company.bsAdjective"],
  ["bsbuzz", "company.bsBuzz"],
  ["bsnoun", "company.bsNoun"],
  ["buzzadjective", "company.buzzAdjective"],
  ["buzznoun", "company.buzzNoun"],
  ["buzzphrase", "company.buzzPhrase"],
  ["buzzverb", "company.buzzVerb"],
  ["catchphrase", "company.catchPhrase"],
  ["catchphraseadjective", "company.catchPhraseAdjective"],
  ["catchphrasedescriptor", "company.catchPhraseDescriptor"],
  ["catchphrasenoun", "company.catchPhraseNoun"],
  ["companysuffix", "company.companySuffix"],
  ["name", "company.name"],
  ["suffixes", "company.suffixes"],
  ["collation", "database.collation"],
  ["column", "database.column"],
  ["engine", "database.engine"],
  ["mongodbobjectid", "database.mongodbObjectId"],
  ["type", "database.type"],
  ["array", "datatype.array"],
  ["bigint", "datatype.bigInt"],
  ["boolean", "datatype.boolean"],
  ["datetime", "datatype.datetime"],
  ["float", "datatype.float"],
  ["hexadecimal", "datatype.hexadecimal"],
  ["json", "datatype.json"],
  ["number", "datatype.number"],
  ["string", "datatype.string"],
  ["uuid", "datatype.uuid"],
  ["anytime", "date.anytime"],
  ["between", "date.between"],
  ["betweens", "date.betweens"],
  ["birthdate", "date.birthdate"],
  ["future", "date.future"],
  ["month", "date.month"],
  ["past", "date.past"],
  ["recent", "date.recent"],
  ["soon", "date.soon"],
  ["weekday", "date.weekday"],
  ["account", "finance.account"],
  ["accountname", "finance.accountName"],
  ["accountnumber", "finance.accountNumber"],
  ["amount", "finance.amount"],
  ["bic", "finance.bic"],
  ["bitcoinaddress", "finance.bitcoinAddress"],
  ["creditcardcvv", "finance.creditCardCVV"],
  ["creditcardissuer", "finance.creditCardIssuer"],
  ["creditcardnumber", "finance.creditCardNumber"],
  ["currency", "finance.currency"],
  ["currencycode", "finance.currencyCode"],
  ["currencyname", "finance.currencyName"],
  ["currencysymbol", "finance.currencySymbol"],
  ["ethereumaddress", "finance.ethereumAddress"],
  ["iban", "finance.iban"],
  ["litecoinaddress", "finance.litecoinAddress"],
  ["mask", "finance.mask"],
  ["maskednumber", "finance.maskedNumber"],
  ["pin", "finance.pin"],
  ["routingnumber", "finance.routingNumber"],
  ["transactiondescription", "finance.transactionDescription"],
  ["transactiontype", "finance.transactionType"],
  ["branch", "git.branch"],
  ["commitdate", "git.commitDate"],
  ["commitentry", "git.commitEntry"],
  ["commitmessage", "git.commitMessage"],
  ["commitsha", "git.commitSha"],
  ["shortsha", "git.shortSha"],
  ["abbreviation", "hacker.abbreviation"],
  ["adjective", "hacker.adjective"],
  ["ingverb", "hacker.ingverb"],
  ["noun", "hacker.noun"],
  ["phrase", "hacker.phrase"],
  ["verb", "hacker.verb"],
  ["arrayelement", "helpers.arrayElement"],
  ["arrayelements", "helpers.arrayElements"],
  ["enumvalue", "helpers.enumValue"],
  ["fake", "helpers.fake"],
  ["fromregexp", "helpers.fromRegExp"],
  ["maybe", "helpers.maybe"],
  ["multiple", "helpers.multiple"],
  ["mustache", "helpers.mustache"],
  ["objectentry", "helpers.objectEntry"],
  ["objectkey", "helpers.objectKey"],
  ["objectvalue", "helpers.objectValue"],
  ["rangetonumber", "helpers.rangeToNumber"],
  ["regexpstylestringparse", "helpers.regexpStyleStringParse"],
  ["replacecreditcardsymbols", "helpers.replaceCreditCardSymbols"],
  ["replacesymbolwithnumber", "helpers.replaceSymbolWithNumber"],
  ["replacesymbols", "helpers.replaceSymbols"],
  ["shuffle", "helpers.shuffle"],
  ["slugify", "helpers.slugify"],
  ["unique", "helpers.unique"],
  ["uniquearray", "helpers.uniqueArray"],
  ["weightedarrayelement", "helpers.weightedArrayElement"],
  ["abstract", "image.abstract"],
  ["animals", "image.animals"],
  ["avatar", "image.avatar"],
  ["avatargithub", "image.avatarGitHub"],
  ["avatarlegacy", "image.avatarLegacy"],
  ["business", "image.business"],
  ["cats", "image.cats"],
  ["city", "image.city"],
  ["datauri", "image.dataUri"],
  ["fashion", "image.fashion"],
  ["food", "image.food"],
  ["image", "image.image"],
  ["imageurl", "image.imageUrl"],
  ["nature", "image.nature"],
  ["nightlife", "image.nightlife"],
  ["people", "image.people"],
  ["sports", "image.sports"],
  ["technics", "image.technics"],
  ["transport", "image.transport"],
  ["url", "image.url"],
  ["urlloremflickr", "image.urlLoremFlickr"],
  ["urlpicsumphotos", "image.urlPicsumPhotos"],
  ["urlplaceholder", "image.urlPlaceholder"],
  ["avatar", "internet.avatar"],
  ["color", "internet.color"],
  ["displayname", "internet.displayName"],
  ["domainname", "internet.domainName"],
  ["domainsuffix", "internet.domainSuffix"],
  ["domainword", "internet.domainWord"],
  ["email", "internet.email"],
  ["emoji", "internet.emoji"],
  ["exampleemail", "internet.exampleEmail"],
  ["httpmethod", "internet.httpMethod"],
  ["httpstatuscode", "internet.httpStatusCode"],
  ["ip", "internet.ip"],
  ["ipv4", "internet.ipv4"],
  ["ipv6", "internet.ipv6"],
  ["mac", "internet.mac"],
  ["password", "internet.password"],
  ["port", "internet.port"],
  ["protocol", "internet.protocol"],
  ["url", "internet.url"],
  ["useragent", "internet.userAgent"],
  ["username", "internet.userName"],
  ["buildingnumber", "location.buildingNumber"],
  ["cardinaldirection", "location.cardinalDirection"],
  ["city", "location.city"],
  ["cityname", "location.cityName"],
  ["country", "location.country"],
  ["countrycode", "location.countryCode"],
  ["county", "location.county"],
  ["direction", "location.direction"],
  ["latitude", "location.latitude"],
  ["longitude", "location.longitude"],
  ["nearbygpscoordinate", "location.nearbyGPSCoordinate"],
  ["ordinaldirection", "location.ordinalDirection"],
  ["secondaryaddress", "location.secondaryAddress"],
  ["state", "location.state"],
  ["stateabbr", "location.stateAbbr"],
  ["street", "location.street"],
  ["streetaddress", "location.streetAddress"],
  ["streetname", "location.streetName"],
  ["timezone", "location.timeZone"],
  ["zipcode", "location.zipCode"],
  ["zipcodebystate", "location.zipCodeByState"],
  ["lines", "lorem.lines"],
  ["paragraph", "lorem.paragraph"],
  ["paragraphs", "lorem.paragraphs"],
  ["sentence", "lorem.sentence"],
  ["sentences", "lorem.sentences"],
  ["slug", "lorem.slug"],
  ["text", "lorem.text"],
  ["word", "lorem.word"],
  ["words", "lorem.words"],
  ["genre", "music.genre"],
  ["songname", "music.songName"],
  ["bigint", "number.bigInt"],
  ["binary", "number.binary"],
  ["float", "number.float"],
  ["hex", "number.hex"],
  ["int", "number.int"],
  ["octal", "number.octal"],
  ["bio", "person.bio"],
  ["firstname", "person.firstName"],
  ["fullname", "person.fullName"],
  ["gender", "person.gender"],
  ["jobarea", "person.jobArea"],
  ["jobdescriptor", "person.jobDescriptor"],
  ["jobtitle", "person.jobTitle"],
  ["jobtype", "person.jobType"],
  ["lastname", "person.lastName"],
  ["middlename", "person.middleName"],
  ["prefix", "person.prefix"],
  ["sex", "person.sex"],
  ["sextype", "person.sexType"],
  ["suffix", "person.suffix"],
  ["zodiacsign", "person.zodiacSign"],
  ["imei", "phone.imei"],
  ["number", "phone.number"],
  ["alpha", "random.alpha"],
  ["alphanumeric", "random.alphaNumeric"],
  ["numeric", "random.numeric"],
  ["word", "random.word"],
  ["words", "random.words"],
  ["chemicalelement", "science.chemicalElement"],
  ["unit", "science.unit"],
  ["alpha", "string.alpha"],
  ["alphanumeric", "string.alphanumeric"],
  ["binary", "string.binary"],
  ["fromcharacters", "string.fromCharacters"],
  ["hexadecimal", "string.hexadecimal"],
  ["nanoid", "string.nanoid"],
  ["numeric", "string.numeric"],
  ["octal", "string.octal"],
  ["sample", "string.sample"],
  ["symbol", "string.symbol"],
  ["uuid", "string.uuid"],
  ["commonfileext", "system.commonFileExt"],
  ["commonfilename", "system.commonFileName"],
  ["commonfiletype", "system.commonFileType"],
  ["cron", "system.cron"],
  ["directorypath", "system.directoryPath"],
  ["fileext", "system.fileExt"],
  ["filename", "system.fileName"],
  ["filepath", "system.filePath"],
  ["filetype", "system.fileType"],
  ["mimetype", "system.mimeType"],
  ["networkinterface", "system.networkInterface"],
  ["semver", "system.semver"],
  ["bicycle", "vehicle.bicycle"],
  ["color", "vehicle.color"],
  ["fuel", "vehicle.fuel"],
  ["manufacturer", "vehicle.manufacturer"],
  ["model", "vehicle.model"],
  ["type", "vehicle.type"],
  ["vehicle", "vehicle.vehicle"],
  ["vin", "vehicle.vin"],
  ["vrm", "vehicle.vrm"],
  ["adjective", "word.adjective"],
  ["adverb", "word.adverb"],
  ["conjunction", "word.conjunction"],
  ["interjection", "word.interjection"],
  ["noun", "word.noun"],
  ["preposition", "word.preposition"],
  ["sample", "word.sample"],
  ["verb", "word.verb"],
  ["words", "word.words"],
]);
