export const dataEntityTypes = [
  "users",
  "posts",
  "comments",
  "albums",
  "reviews",
  "todos",
  "addresses",
  "companies",
  "products",
  "payments",
  "vehicles",
  "files",
  "socialmediaprofiles",
  "educationalinstitutions",
  "financialtransactions",
  "healthrecords",
  "realestatelistings",
  "travelplans",
  "recipes",
  "orders",
] as const;

export const fakerModules = [
  "address",
  "animal",
  "color",
  "commerce",
  "company",
  "database",
  "date",
  "finance",
  "git",
  "hacker",
  "image",
  "internet",
  "lorem",
  "location",
  "music",
  "name",
  "phone",
  "random",
  "science",
  "system",
  "vehicle",
] as const;

export const fakerFormats = [
  "json",
  "yaml",
  "xml",
  "html",
  "raw",
  "csv",
  "text",
  "form",
  "pdf",
  "markdown",
  "binary",
] as const;

// https://developers.google.com/analytics/devguides/reporting/core/v3/reference#filters
export const filterOperators = [
  "==",
  "!=",
  ">",
  "<",
  ">=",
  "<=",
  "=@",
  "!@",
  "=~",
  "!~",
];

export const supportedLocalization = [
  "af_ZA",
  "ar",
  "az",
  "base",
  "cs_CZ",
  "da",
  "de",
  "de_AT",
  "de_CH",
  "dv",
  "el",
  "en",
  "en_AU",
  "en_AU_ocker",
  "en_BORK",
  "en_CA",
  "en_GB",
  "en_GH",
  "en_HK",
  "en_IE",
  "en_IN",
  "en_NG",
  "en_US",
  "en_ZA",
  "eo",
  "es",
  "es_MX",
  "fa",
  "fi",
  "fr",
  "fr_BE",
  "fr_CA",
  "fr_CH",
  "fr_LU",
  "fr_SN",
  "he",
  "hr",
  "hu",
  "hy",
  "id_ID",
  "it",
  "ja",
  "ka_GE",
  "ko",
  "lv",
  "mk",
  "nb_NO",
  "ne",
  "nl",
  "nl_BE",
  "pl",
  "pt_BR",
  "pt_PT",
  "ro",
  "ro_MD",
  "ru",
  "sk",
  "sr_RS_latin",
  "sv",
  "th",
  "tr",
  "uk",
  "ur",
  "vi",
  "yo_NG",
  "zh_CN",
  "zh_TW",
  "zu_ZA",
] as const;

export const supportedLocalizationMap = new Map([
  ["af_ZA", ["Afrikaans (South Africa)", "fakerAF_ZA"]],
  ["ar", ["Arabic", "fakerAR"]],
  ["az", ["Azerbaijani", "fakerAZ"]],
  ["base", ["Base", "fakerBASE"]],
  ["cs_CZ", ["Czech (Czechia)", "fakerCS_CZ"]],
  ["da", ["Danish", "fakerDA"]],
  ["de", ["German", "fakerDE"]],
  ["de_AT", ["German (Austria)", "fakerDE_AT"]],
  ["de_CH", ["German (Switzerland)", "fakerDE_CH"]],
  ["dv", ["Maldivian", "fakerDV"]],
  ["el", ["Greek", "fakerEL"]],
  ["en", ["English", "fakerEN"]],
  ["en_AU", ["English (Australia)", "fakerEN_AU"]],
  ["en_AU_ocker", ["English (Australia Ocker)", "fakerEN_AU_ocker"]],
  ["en_BORK", ["English (Bork)", "fakerEN_BORK"]],
  ["en_CA", ["English (Canada)", "fakerEN_CA"]],
  ["en_GB", ["English (Great Britain)", "fakerEN_GB"]],
  ["en_GH", ["English (Ghana)", "fakerEN_GH"]],
  ["en_HK", ["English (Hong Kong)", "fakerEN_HK"]],
  ["en_IE", ["English (Ireland)", "fakerEN_IE"]],
  ["en_IN", ["English (India)", "fakerEN_IN"]],
  ["en_NG", ["English (Nigeria)", "fakerEN_NG"]],
  ["en_US", ["English (United States)", "fakerEN_US"]],
  ["en_ZA", ["English (South Africa)", "fakerEN_ZA"]],
  ["eo", ["Esperanto", "fakerEO"]],
  ["es", ["Spanish", "fakerES"]],
  ["es_MX", ["Spanish (Mexico)", "fakerES_MX"]],
  ["fa", ["Farsi/Persian", "fakerFA"]],
  ["fi", ["Finnish", "fakerFI"]],
  ["fr", ["French", "fakerFR"]],
  ["fr_BE", ["French (Belgium)", "fakerFR_BE"]],
  ["fr_CA", ["French (Canada)", "fakerFR_CA"]],
  ["fr_CH", ["French (Switzerland)", "fakerFR_CH"]],
  ["fr_LU", ["French (Luxembourg)", "fakerFR_LU"]],
  ["fr_SN", ["French (Senegal)", "fakerFR_SN"]],
  ["he", ["Hebrew", "fakerHE"]],
  ["hr", ["Croatian", "fakerHR"]],
  ["hu", ["Hungarian", "fakerHU"]],
  ["hy", ["Armenian", "fakerHY"]],
  ["id_ID", ["Indonesian (Indonesia)", "fakerID_ID"]],
  ["it", ["Italian", "fakerIT"]],
  ["ja", ["Japanese", "fakerJA"]],
  ["ka_GE", ["Georgian (Georgia)", "fakerKA_GE"]],
  ["ko", ["Korean", "fakerKO"]],
  ["lv", ["Latvian", "fakerLV"]],
  ["mk", ["Macedonian", "fakerMK"]],
  ["nb_NO", ["Norwegian (Norway)", "fakerNB_NO"]],
  ["ne", ["Nepali", "fakerNE"]],
  ["nl", ["Dutch", "fakerNL"]],
  ["nl_BE", ["Dutch (Belgium)", "fakerNL_BE"]],
  ["pl", ["Polish", "fakerPL"]],
  ["pt_BR", ["Portuguese (Brazil)", "fakerPT_BR"]],
  ["pt_PT", ["Portuguese (Portugal)", "fakerPT_PT"]],
  ["ro", ["Romanian", "fakerRO"]],
  ["ro_MD", ["Romanian (Moldova)", "fakerRO_MD"]],
  ["ru", ["Russian", "fakerRU"]],
  ["sk", ["Slovak", "fakerSK"]],
  ["sr_RS_latin", ["Serbian (Serbia, Latin)", "fakerSR_RS_latin"]],
  ["sv", ["Swedish", "fakerSV"]],
  ["th", ["Thai", "fakerTH"]],
  ["tr", ["Turkish", "fakerTR"]],
  ["uk", ["Ukrainian", "fakerUK"]],
  ["ur", ["Urdu", "fakerUR"]],
  ["vi", ["Vietnamese", "fakerVI"]],
  ["yo_NG", ["Yoruba (Nigeria)", "fakerYO_NG"]],
  ["zh_CN", ["Chinese (China)", "fakerZH_CN"]],
  ["zh_TW", ["Chinese (Taiwan)", "fakerZH_TW"]],
  ["zu_ZA", ["Zulu (South Africa)", "fakerZU_ZA"]],
]);
